name: .NET Framework 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: nuget restore "PS4 Cheat Engine.sln"

    - name: Build
      run: msbuild "PS4 Cheat Engine.sln" /p:Configuration=Release

    - name: Run tests
      run: |
        if (Test-Path -Path .\PS4Cheater\PS4 Cheat Engine.Tests\bin\Release\PS4 Cheat Engine.Tests.dll) {
          vstest.console.exe .\PS4Cheater\PS4 Cheat Engine.Tests\bin\Release\PS4 Cheat Engine.Tests.dll
        }
