name: .NET Framework Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.8.x'

    - name: Restore dependencies
      run: nuget restore PS4\ Cheat\ Engine.sln

    - name: Build
      run: msbuild PS4\ Cheat\ Engine.sln /p:Configuration=Release

    - name: Run tests
      run: |
        if (Test-Path -Path .\PS4\ Cheat\ Engine.Tests\bin\Release\PS4\ Cheat\ Engine.Tests.dll) {
          vstest.console.exe .\PS4\ Cheat\ Engine.Tests\bin\Release\PS4\ Cheat\ Engine.Tests.dll
        }
